spring:
  datasource:
    url: jdbc:mysql://localhost:13308/spring_context_test?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver


logging:
  level:
    root: debug
mybatis:
  type-aliases-package: com.example.springdbpooltest.model
